name: "Cache assets"

runs:
  using: "composite"
  steps:
    - name: Cache assets
      id: cache-assets
      uses: actions/cache@v3
      env:
        cache-name: cache-assets
      with:
        path: |
          ${{ github.workspace }}/assets
        key: ${{ runner.os }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ github.run_id }}