name: "Setup modules"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_modules
    - name: Cache node modules
      id: cache-node-modules-puppeteer
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules-puppeteer
      with:
        path: |
          ${{ github.workspace }}/node_modules
        key: ${{ runner.os }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
    - name: Argos - Prepare env
      if: ${{ steps.cache-node-modules-puppeteer.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        yarn add puppeteer@"21.11.0" --dev --exact